### ISSUE TITLE
Overriding Redirect extension path

### ISSUE THREAD

**Issue by olevett** [statiqdev/Statiq.Framework#105]
I've been setting up a site first with Wyam and now Statiq, and have hit an  issue with redirects. In both, redirect files are always output as .html files (https://github.com/statiqdev/Statiq.Framework/blob/master/src/core/Statiq.Core/Modules/Content/GenerateRedirects.cs#L152) but I'm trying to redirect from some content with "htm" extensions.

I think it would make sense to add a parameter to GenerateRedirects something like WithExtension or OverrideExtension or similar, to either allow changing this behaviour, or disabling it in certain circumstances.

Does that make sense/have I missed something super obvious?

**Comment by daveaglick** [comment]
Want to make sure I understand the issue. You’re saying that when you create a document with `RedirectFrom: /foo/bar.htm` there’s an assumption that the source file has an `html` extension so you actually get `/foo/bar.htm.html` as a client redirect file? Yeah, I can see how that’s a bug (or at least a problem).

I’m sure there’s a relatively easy fix for this (assuming I understood the problem). I’ll try to get it fixed in the next release.

**Comment by olevett** [comment]
Yeah, exactly that, sorry it wasn't particularly clear.

`Foo.html` as a RedirectFrom gets a file at `Foo.html` but `Foo.htm` generates a file at `Foo.htm.html`>

**Comment by daveaglick** [comment]
Got it, thanks. I think this is a bug then and I'll get it fixed in the next release.

**Comment by daveaglick** [comment]
Instead of adding a flag to keep the original path without adding `.html`, I think I'll just add an extra check so we don't add a new extension for `.html` _or_ `.htm`. Any other extension doesn't make a ton of sense given the module generates client-side HTML redirect files.

That way, when `RedirectFrom` is...:
- `Foo.html` generates a redirect file at `Foo.html`
- `Foo.htm` generates a redirect file at `Foo.htm`
- `Foo` generates a redirect file at `Foo.html`
- `Foo.bar` generates a redirect file at `Foo.bar.html`

**Comment by olevett** [comment]
👍  that sounds great, thanks @daveaglick!
