### ISSUE TITLE
'--help' CLI option throws error in Statiq.Framework 1.0.0-beta.41

### ISSUE THREAD

**Issue by harrison314** [statiqdev/Statiq.Framework#186]
Running a _Statiq.Framework  1.0.0-beta.41_ app with options **--help** command always results in this error message:

```
Error: Could not find color or style 'analyzer'.
```

My bootstraper code:

```cs
return await Bootstrapper
                .Factory.Create(args)
                .AddDefaultShortcodes()
                .AddGlobCommands()
                .AddDefaults(DefaultFeatures.BuildCommands | DefaultFeatures.Logging| DefaultFeatures.Pipelines)
                .AddPipeline<Pipelines.AssertPipeline>()
                .AddPipeline<Pipelines.RazorPipeline>()
                .AddPipeline<Pipelines.BlogPipeline>()
                .AddSetting(Keys.LinkLowercase, false)
                .AddSetting(Keys.LinksUseHttps, true)
                .AddSetting(Keys.LinkHideExtensions, false)
                .AddSetting(BlogKeys.UseAbsoluteUrls, false)
                .AddSetting(Keys.Host, "harrison314.github.io")
                .AddSetting(Keys.Title, "harrison314 blog")
                .AddSetting(FeedKeys.Author, "harrison314")
                .AddSetting(FeedKeys.Description, "Blog jedného skeptického programátora.")
                .AddSetting(FeedKeys.Copyright, $"harrison314 © {DateTime.UtcNow.Year.ToString()}")
                .AddSetting(BlogKeys.MinifyOutput, false)
                .AddSetting(BlogKeys.GithubRepo, "https://github.com/harrison314/")
                .RunAsync();
```

**Comment by patriksvensson** [comment]
That's Spectre.Console. Try updating the version to the latest one if possible.

**Comment by harrison314** [comment]
Using the _Spectre.Console_ in versions 0.38.0 and 0.39.0 program throws next error:

```
Unhandled exception. System.TypeLoadException: Method 'RegisterLazy' in type 'Statiq.App.CommandServiceTypeRegistrar' from assembly 'Statiq.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Statiq.App.Bootstrapper..ctor(String[] arguments)
   at Statiq.App.BootstrapperFactory.Create(String[] args)
   at Harrison314Blog.Program.Main(String[] args) 
```

**Comment by patriksvensson** [comment]
Seems like there are two versions of Statiq referencing different versions of Spectre.Console.

**Comment by daveaglick** [comment]
> Seems like there are two versions of Statiq referencing different versions of Spectre.Console.

The only Spectre.Console reference is in Statiq.App - is gets brought into everything else transitively. I'll guess that the missing method exception happened because Statiq.App (and other Statiq Libraries) are bound to Spectre.Console 0.37.0 so when you updated Spectre.Console locally it broke that binding due to method differences (that's mostly to be expected).

The real question is why you're seeing an error with the help command in the first place. I can replicate, so best thing now is probably to update the Spectre.Console version in use by Statiq officially since updating locally creates a compatibility break. I'll do that for the next release (out in a day or two, just finishing up a few caching things).

![image](https://user-images.githubusercontent.com/1020407/116468115-76d45e00-a83e-11eb-8dac-f4f72bbfdf08.png)

**Comment by patriksvensson** [comment]
@daveaglick Any `[` or `]` in descriptions must be escaped since we allow markup there.

![image](https://user-images.githubusercontent.com/357872/116510136-b9d91480-a8c4-11eb-8aa0-e50cd33a1c1e.png)

**Comment by daveaglick** [comment]
Ah, that makes sense @patriksvensson, I'm guessing I've got at least one set of brackets somewhere carried over from Spectre.Cli use. Should be easy enough to fix up.

**Comment by patriksvensson** [comment]
@daveaglick The `CommandOption` and `CommandAttribute` should not be escaped. Only things like descriptions.

**Comment by patriksvensson** [comment]
@daveaglick I can submit a PR for this if you want

**Comment by daveaglick** [comment]
Nah, I'll get it...unless you _really_ want to :)

**Comment by daveaglick** [comment]
Thanks for the bug report!
