### ISSUE TITLE
Dependencies not respected for clean builds

### ISSUE THREAD

**Issue by VikeMK** [statiqdev/Statiq.Framework#214]
I recently started a blog using Statiq.Web and I was struggling to figure out how I can get my favicon to override the one provided by the CleanBlog theme. Since there is a favicon.ico already inside the theme I was using, I created a pipeline which had a dependency on Inputs as follows:

```csharp
public class FaviconPipeline : Pipeline
{
    public FaviconPipeline()
    {
        Dependencies.Add(nameof(Inputs));
        InputModules = new() { new ReadFiles("assets/favicon/favicon.ico") };
        ProcessModules = new() { new SetDestination("favicon.ico") };
        OutputModules = new() { new WriteFiles() };
    }
}
```

However, when I delete my output folder and run it from a clean state, the Inputs pipeline runs after my Favicon pipeline, and so the favicon.ico from the theme overrides my custom one. When I run it a second time when the output folder exists, it seems that the dependencies then get respected and my Favicon pipeline runs after Inputs and my custom favicon gets used.

The repo which demonstrates this issue can be found here: https://github.com/VikeMK/vikemk.github.io

To work around this issue, I updated my github workflow to build the site twice ([link](https://github.com/VikeMK/vikemk.github.io/blob/main/.github/workflows/main.yml#L15-L16))

Here is an example run of the workflow which runs it twice with debug logging on: [link](https://github.com/VikeMK/vikemk.github.io/runs/4246179278?check_suite_focus=true#step:4:1)

**Comment by daveaglick** [comment]
Creating a pipeline is definitely one way to approach this, but there’s a way easier way too! The theme folder and the input folder get combined in a “virtual file system”. The trick here is that the input folder takes precedence. So any file that exists in the theme folder can be “overridden” by a file with the same name in the input folder. In other words, to override the favicon.ico file from the theme, add a favicon.ico file to your input folder and it’ll take precedence.

Try that and let me know if it works for you. And if so, I’d welcome any suggests on where and how to document this behavior so it’s more discoverable.

**Comment by daveaglick** [comment]
My comment above doesn’t really address the problem you were originally seeing though. I think what’s happening there is that you’re seeing a race condition on file writing since both the Assets pipeline and your Favicon pipeline are trying to write the same `/favicon.ico` file. The first time through, your pipeline wins since it’s so simple (and “winning” means it writes first and the. Gets overwritten). Then the second time through the timing changes (probably due to caching which speeds up the built-in pipelines on subsequent generations) and the Asset pipeline wins so it gets overwritten with your file. This behavior is somewhat expected - you hopefully saw a warning in the console about writing to the same path as well. In general, it’s a good idea not to have different pipelines writing to the same path because the write process is concurrent and the timing isn’t usually deterministic.

That’s all not really important given my first comment, but figured it might be helpful to explain.

**Comment by VikeMK** [comment]
Your solution worked for me. For some reason I thought only certain file types were copied from input to output and that all asset files such as .ico had to be in the assets folder, thanks for the clarification
